"""CPU-only, fail-closed SFT readiness audit; never trains or calls a model.

Historical replay verifies previously recorded model outputs in their original
environment. It is NOT a new inference evaluation. A new RP policy evaluation
must be separately generated by train_policy, then checked by this program.
"""
from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from copy import deepcopy
from datetime import datetime, timezone
import hashlib
import importlib
import inspect
import json
import math
from pathlib import Path
import random
import sys

SCHEMA = "mito.rp-grpo.sft-gate.v1"
ROOT = Path(__file__).resolve().parents[1]
REQUIRED_BINDINGS = (
    "base_snapshot_sha256", "initial_adapter_sha256", "training_data_sha256",
    "scorers_sha256", "data_manifest_sha256", "environment_sha256", "prompt_contract_sha256", "evaluation_report_sha256",
)


def file_hash(path: Path) -> str:
    with path.open("rb") as handle:
        return hashlib.file_digest(handle, "sha256").hexdigest()


def canonical_hash(value) -> str:
    return hashlib.sha256(json.dumps(value, ensure_ascii=False, sort_keys=True,
                                    separators=(",", ":"), allow_nan=False).encode()).hexdigest()


def strict_json(text: str):
    def pairs(items):
        result = {}
        for key, value in items:
            if key in result:
                raise ValueError(f"duplicate JSON key: {key}")
            result[key] = value
        return result
    def constant(value):
        raise ValueError(f"nonfinite JSON value: {value}")
    def finite(value):
        number = float(value)
        if not math.isfinite(number):
            raise ValueError("nonfinite JSON number")
        return number
    return json.loads(text, object_pairs_hook=pairs, parse_constant=constant, parse_float=finite)


def read_json(path: Path):
    return strict_json(path.read_text(encoding="utf-8"))


def read_jsonl(path: Path) -> list[dict]:
    rows = [strict_json(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    if not rows or any(not isinstance(row, dict) for row in rows):
        raise ValueError("nonempty JSONL object records required")
    return rows


def write_new(path: Path, value) -> None:
    if path.exists() or path.is_symlink():
        raise ValueError(f"refusing to overwrite existing audit: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("x", encoding="utf-8") as handle:
        handle.write(json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False) + "\n")


def model_snapshot(model: Path) -> dict:
    model = model.resolve(strict=True)
    index = read_json(model / "model.safetensors.index.json")
    names = set(index["weight_map"].values()) | {
        "config.json", "model.safetensors.index.json", "tokenizer.json", "tokenizer_config.json"}
    if any(Path(name).name != name for name in names):
        raise ValueError("model index must use local shard basenames")
    config = read_json(model / "config.json")
    if (config.get("model_type"), config.get("hidden_size"), config.get("num_hidden_layers")) != ("qwen3", 2560, 36):
        raise ValueError("expected Qwen3-4B architecture")
    digests = {name: file_hash(model / name) for name in sorted(names)}
    return {"files_sha256": digests, "base_snapshot_sha256": canonical_hash(digests)}


def tokenizer_compatibility(model: Path, adapter: Path) -> dict:
    """Compare behavior on CPU, not merely serialized JSON file equality."""
    from transformers import AutoTokenizer
    base = AutoTokenizer.from_pretrained(model, local_files_only=True, trust_remote_code=False)
    saved = AutoTokenizer.from_pretrained(adapter, local_files_only=True, trust_remote_code=False)
    probes = ["查找 TMRM 与 ATP 条件限定原文。", "3/8/15 mM glucose β-cell μs τ",
              '<tool_call>{"name":"get_evidence","arguments":{"evidence_id":"S1"}}</tool_call>']
    return {
        "vocabulary_equal": base.get_vocab() == saved.get_vocab(),
        "chat_template_equal": base.get_chat_template() == saved.get_chat_template(),
        "probe_token_ids_equal": all(base.encode(text) == saved.encode(text) for text in probes),
        "base_pad_token_id": base.pad_token_id, "adapter_pad_token_id": saved.pad_token_id,
        "base_eos_token_id": base.eos_token_id, "adapter_eos_token_id": saved.eos_token_id,
        "serialized_files_sha256": {name: {"base": file_hash(model / name),
            "adapter": file_hash(adapter / name)} for name in ("tokenizer.json", "tokenizer_config.json")},
        "required_loader": "Load tokenizer from explicit package model path, not adapter directory.",
        "historical_generation_pad_token_id": base.eos_token_id,
        "note": "Old SFT saved pad=EOS; historical evaluation loaded the base tokenizer and supplied generation pad=EOS. Different saved bytes are not a different vocabulary.",
    }


def stable(value):
    """Only runtime timings may differ in deterministic replay."""
    if isinstance(value, dict):
        return {key: stable(child) for key, child in value.items()
                if key not in {"latency_ms", "latency_seconds"}}
    if isinstance(value, list):
        return [stable(child) for child in value]
    return value


def replay_content(trace: dict) -> dict:
    """A new execution has new timing but must preserve all semantic records."""
    result = deepcopy(trace)
    result.pop("trace_sha256", None)
    timing = result.get("telemetry", {})
    timing.pop("wall_time_s", None)
    timing.pop("per_call_seconds", None)
    return result


def validate_policy_tokens(step: dict, tokenizer, prompt: str, episode: dict,
                           config: dict) -> None:
    """Check recorded model bytes without treating a budget stop as corruption."""
    tokens = step.get("tokens") or step.get("token_record") or {
        "prompt_ids": step.get("prompt_ids"), "completion_ids": step.get("completion_ids")}
    if not isinstance(tokens, dict):
        raise ValueError("actual evaluation must retain token IDs")
    prompt_ids = tokenizer.encode(prompt, add_special_tokens=False)
    if tokens.get("prompt_ids") != prompt_ids:
        raise ValueError("actual prompt tokens differ from deployed tokenization")
    completion_ids = tokens.get("completion_ids")
    if not isinstance(completion_ids, list) or any(type(value) is not int or value < 0 for value in completion_ids):
        raise ValueError("missing/invalid actual completion token IDs")
    if step.get("policy_tokens_sha256") != canonical_hash(completion_ids):
        raise ValueError("generated policy token hash mismatch")
    if step.get("prompt_tokens") != len(prompt_ids) or step.get("completion_tokens") != len(completion_ids):
        raise ValueError("reported token counts differ from actual IDs")
    if tokenizer.decode(completion_ids, skip_special_tokens=True) != step["raw_text"]:
        raise ValueError("model text differs from generated token IDs")
    ended = bool(completion_ids and completion_ids[-1] == tokenizer.eos_token_id)
    if type(step.get("terminated")) is not bool or ended != step["terminated"]:
        raise ValueError("generation termination flag differs from tokens")
    if not completion_ids:
        if (episode.get("termination_reason") != "context_budget"
                or len(prompt_ids) + int(config["max_new_tokens"]) <= int(config["max_context_tokens"])
                or "action" in step or "result" in step):
            raise ValueError("empty completion without an actual context-budget stop")
    if len(completion_ids) > int(config["max_new_tokens"]):
        raise ValueError("completion exceeds the frozen generation budget")


def interval(successes: int, total: int) -> list[float] | None:
    if not total:
        return None
    z = 1.959963984540054
    p = successes / total
    denominator = 1 + z * z / total
    center = (p + z * z / (2 * total)) / denominator
    delta = z * math.sqrt(p * (1 - p) / total + z * z / (4 * total * total)) / denominator
    return [center - delta, center + delta]


def grouped_interval(rows: list[dict], key: str, *, seed: int = 20260909) -> dict:
    groups = defaultdict(list)
    for row in rows:
        groups[row[key]].append(bool(row["success"]))
    if len(groups) < 2:
        return {"n_groups": len(groups), "ci95": None, "reason": "insufficient independent groups"}
    values = list(groups.values())
    rng = random.Random(seed)
    draws = []
    for _ in range(2000):
        selected = [item for _ in values for item in rng.choice(values)]
        draws.append(sum(selected) / len(selected))
    draws.sort()
    return {"n_groups": len(groups), "ci95": [draws[49], draws[1949]],
            "seed": seed, "bootstrap_samples": 2000,
            "warning": "Repeated templates and few sources limit inference; a degenerate interval is not certainty."}


def verify_split(task_dir: Path) -> dict:
    groups = {}
    manifest = read_json(task_dir / "manifest.json")
    for split, filename in (("train", "train.jsonl"), ("development", "development.jsonl"), ("test", "test.jsonl")):
        path = task_dir / filename
        rows = read_jsonl(path)
        entry = manifest["files"][filename]
        want = entry["sha256"] if isinstance(entry, dict) else entry
        if file_hash(path) != want or any(row["split"] != split for row in rows):
            raise ValueError(f"split/hash mismatch: {split}")
        groups[split] = {
            "rows": len(rows), "task_ids": {row["task_id"] for row in rows},
            "pair_ids": {row["pair_id"] for row in rows},
            "paper_ids": {paper for row in rows for paper in row["provenance"]["paper_ids"]},
            "sha256": file_hash(path),
        }
    overlaps = {}
    for a, b in (("train", "development"), ("train", "test"), ("development", "test")):
        overlaps[f"{a}__{b}"] = {field: sorted(groups[a][field] & groups[b][field])
            for field in ("task_ids", "pair_ids", "paper_ids")}
    if any(values for overlap in overlaps.values() for values in overlap.values()):
        raise ValueError("cross-split leakage in historical source/task/pair grouping")
    return {"status": "PASS", "overlaps": overlaps, "splits": {split: {
        "rows": data["rows"], "pairs": len(data["pair_ids"]), "papers": len(data["paper_ids"]),
        "sha256": data["sha256"]} for split, data in groups.items()},
        "test_already_opened": True, "test_usable_for_new_model_selection": False,
        "scope": "Exact recorded task, pair and paper IDs; not proof against pretraining contamination."}


def legacy_audit(legacy_root: Path, model: Path, *, adapter: Path | None = None) -> dict:
    root = legacy_root.resolve(strict=True)
    training = root / "training_runs/evidence-tool-sft-20260906-v2/training"
    adapter = adapter or training / "adapter"
    evaluation = root / "training_runs/source-tools-test-20260906-v1-sft"
    manifest = read_json(evaluation / "manifest.json")
    train_manifest = read_json(training / "run_manifest.json")
    if manifest.get("status") != "completed" or train_manifest.get("status") != "completed":
        raise ValueError("historical SFT/evaluation is not complete")
    for name, expected in manifest["source_sha256"].items():
        if Path(name).name != name or file_hash(root / "training" / name) != expected:
            raise ValueError(f"historical evaluator source changed: {name}")
    if file_hash(adapter / "adapter_model.safetensors") != manifest["adapter_sha256"] or manifest["adapter_sha256"] != train_manifest["adapter_sha256"]:
        raise ValueError("historical adapter bytes differ from evaluated SFT")
    if file_hash(adapter / "adapter_config.json") != manifest["adapter_config_sha256"]:
        raise ValueError("historical adapter configuration changed")
    snapshot = model_snapshot(model)
    reference = train_manifest["model_attestation"]["files_sha256"]
    if snapshot["files_sha256"] != reference or reference != manifest["model_attestation"]["files_sha256"]:
        raise ValueError("package base/tokenizer is not the exact historical base")
    task_dir = root / "data/training/local/primary_tool_tasks_v3"
    tasks = {row["task_id"]: row for row in read_jsonl(task_dir / "test.jsonl")}
    if file_hash(task_dir / "test.jsonl") != manifest["task_file_sha256"]:
        raise ValueError("historical evaluation task file changed")
    records = read_jsonl(evaluation / "episodes.jsonl")
    ids = [row["task_id"] for row in records]
    if len(ids) != len(set(ids)) or ids != manifest["task_ids"] or set(ids) != set(tasks):
        raise ValueError("missing/duplicate/reordered historical evaluation task IDs")
    sys.path.insert(0, str(root))
    try:
        evaluator = importlib.import_module("training.evaluate_policy")
        policy = importlib.import_module("training.tool_policy")
        if Path(evaluator.__file__).resolve() != root / "training/evaluate_policy.py":
            raise ValueError("unexpected training module imported")
        schemas = policy.tool_schemas()
        if canonical_hash(schemas) != manifest["tool_schemas_sha256"]:
            raise ValueError("tool schemas differ from historical generation")
        replayed = []
        for record in records:
            cursor = iter(record["assistant_turns"])
            def generate(messages, _schemas):
                turn = next(cursor)
                # Match the actual prefix recorded before this historical call.
                prior = record["messages"][:len(messages)]
                for left, right in zip(messages, prior, strict=True):
                    left, right = deepcopy(left), deepcopy(right)
                    if left.get("role") == "tool":
                        left["content"] = stable(strict_json(left["content"]))
                        right["content"] = stable(strict_json(right["content"]))
                    if left != right:
                        raise ValueError("recorded model prompt history does not replay")
                return turn["raw_text"], turn["generated_tokens"]
            result = evaluator.evaluate_task(tasks[record["task_id"]], generate, schemas)
            if next(cursor, None) is not None:
                raise ValueError("historical raw assistant turns remain unconsumed")
            for key in ("success", "reward", "trace", "completion", "error", "tool_call_guard"):
                if stable(result[key]) != stable(record[key]):
                    raise ValueError(f"historical actual trajectory replay differs: {record['task_id']} {key}")
            replayed.append(result)
    finally:
        sys.path.remove(str(root))
    by_family = defaultdict(list)
    pairs = defaultdict(list)
    schema_valid, call_count, returned_target = 0, 0, 0
    rejection_cases, recovery_success = 0, 0
    failures = []
    for row in replayed:
        task = tasks[row["task_id"]]
        family = task["task_type"]
        by_family[family].append(row)
        pairs[row["pair_id"]].append(row)
        for turn in row["assistant_turns"]:
            for call in evaluator.parse_tool_calls(turn["raw_text"]):
                call_count += 1
                inspect.signature(getattr(policy.EvidenceToolAdapter(), call["name"])).bind(**call["arguments"])
                schema_valid += 1
        allowed = set(task["expected"]["allowed_evidence_ids"])
        if any(event["tool"] == "get_evidence" and event["ok"] and event["result"].get("evidence_id") in allowed for event in row["trace"]):
            returned_target += 1
        rejected = any(event["tool"] == "verify_claim" and event["result"].get("status") == "REJECT" for event in row["trace"])
        if rejected:
            rejection_cases += 1
            recovery_success += bool(row["success"])
        if not row["success"]:
            failures.append({"task_id": row["task_id"], "task_type": family,
                "reason": row["reward"]["reasons"], "terminal_action": row["trace"][-1]["tool"] if row["trace"] else None})
    sensitive, same_question = 0, 0
    for pair in pairs.values():
        if len(pair) != 2 or tasks[pair[0]["task_id"]]["question"] != tasks[pair[1]["task_id"]]["question"]:
            raise ValueError("historical pairs are not the same question")
        same_question += 1
        a, b = pair[0]["trace"], pair[1]["trace"]
        if len(a) >= 2 and len(b) >= 2 and a[0]["arguments"] == b[0]["arguments"] and a[0]["result"] != b[0]["result"] and (a[1]["tool"], a[1]["arguments"]) != (b[1]["tool"], b[1]["arguments"]):
            sensitive += 1
    successes = sum(row["success"] for row in replayed)
    source_rows = [{"success": row["success"], "paper": row["paper_ids"][0]} for row in replayed]
    return {"schema": "mito.sft-readiness.historical.v1", "status": "LIMITED_HISTORICAL_EVIDENCE",
        "new_model_inference_performed": False, "replay_scope": "Recorded actual model text replayed through hash-matched original local tools, not freshly generated predictions.",
        "base_compatibility": {"status": "PASS", **snapshot, "remote_revision": None,
            "adapter_sha256": file_hash(adapter / "adapter_model.safetensors"),
            "adapter_config_sha256": file_hash(adapter / "adapter_config.json"),
            "tokenizer": tokenizer_compatibility(model, adapter)},
        "split_audit": verify_split(task_dir),
        "source_artifacts": {"evaluation_manifest": {"path": str(evaluation / "manifest.json"), "sha256": file_hash(evaluation / "manifest.json")},
            "episodes": {"path": str(evaluation / "episodes.jsonl"), "sha256": file_hash(evaluation / "episodes.jsonl")},
            "training_manifest": {"path": str(training / "run_manifest.json"), "sha256": file_hash(training / "run_manifest.json")},
            "environment_sources": manifest["source_sha256"]},
        "training": {"episodes": train_manifest["episodes"], "assistant_decisions": train_manifest["assistant_decisions"],
            "steps": train_manifest["steps"], "elapsed_seconds": train_manifest["elapsed_seconds"],
            "training_data_sha256": train_manifest["dataset_sha256"], "loss_scope": train_manifest["loss_scope"],
            "origin": "Programmatic reference policy actually executed tools; not expert tool trajectories."},
        "replay": {"records": len(replayed), "records_matched": len(replayed), "tool_calls": call_count,
            "schema_binding_valid_calls": schema_valid, "successes": successes,
            "success_rate": successes / len(replayed), "wilson95_episode_descriptive_only": interval(successes, len(replayed)),
            "source_cluster_bootstrap": grouped_interval(source_rows, "paper"),
            "pairs": len(pairs), "pair_both_success": sum(all(r["success"] for r in p) for p in pairs.values()),
            "target_passages_read": returned_target, "answerable_tasks": sum(r["expected_answerability"] == "answerable" for r in replayed),
            "same_question_pairs": same_question, "changed_action_after_changed_observation_pairs": sensitive,
            "verification_rejection_cases": rejection_cases, "successful_recovery_after_rejection": recovery_success,
            "by_task_family": {name: {"n": len(rows), "successes": sum(r["success"] for r in rows)} for name, rows in by_family.items()},
            "failures": failures},
        "limitations": ["Literal anchor retrieval and exact extraction, not semantic scientific support.",
            "All four original model arms retrieved 40/40 target passages; SFT did not establish retrieval/content improvement.",
            "The 80 historical test episodes are already opened and are not new RP development or hidden-test data.",
            "No new-RP tool contract, feedback-repair, multi-path or end-to-end gate is established by historical replay."]}


def blocked_gate(reason: str, *, legacy: dict | None = None) -> dict:
    items = [
        ("tool_understanding", "正确理解工具定义，并选择合法且相关的工具"),
        ("schema_arguments", "实际 schema 和参数合法"),
        ("feedback_adaptation", "根据返回与错误反馈继续、修复或恰当停止"),
        ("end_to_end", "实际模型在独立任务上的可验证端到端成功"),
    ]
    return {"schema": SCHEMA, "created_at": datetime.now(timezone.utc).isoformat(),
        "passed": False, "status": "BLOCK", "reason": reason,
        "checks": [{"id": key, "description": label, "status": "BLOCK", "reason": reason} for key, label in items],
        "multipath_environment_gate": {"status": "BLOCK", "reason": "Need two successful executable paths and actual policy choices on the same eligible tasks."},
        "historical_evidence": legacy, "bindings": {key: None for key in REQUIRED_BINDINGS},
        "training_authorized_by_this_gate": False, "production_ready": False,
        "note": "A CPU reference/replay pass is not an actual policy pass in the RP environment."}


def feedback_continuation_changed(available: dict, missing: dict) -> bool:
    """Require an identical action prefix until the actual feedback differs.

    Different first guesses under stochastic sampling are not evidence that
    the policy read a changed observation. This is behavioral evidence, not a
    counterfactual causal estimate under coupled random-number draws.
    """
    if available["initial_sha256"] != missing["initial_sha256"] or not (available["success"] and missing["success"]):
        return False
    aa, ba = available["action_hashes"], missing["action_hashes"]
    ao, bo = available["observation_hashes"], missing["observation_hashes"]
    for index in range(min(len(aa), len(ba), len(ao), len(bo))):
        if aa[index] != ba[index]:
            return False
        if ao[index] != bo[index]:
            return bool(aa[index + 1:] and ba[index + 1:] and aa[index + 1:] != ba[index + 1:])
    return False


def decision_checks(rows: list[dict], *, min_success: float = .9,
                    min_schema: float = 1.0, min_pairs: int = 2,
                    min_repair: int = 2, min_families: int = 2) -> dict:
    """Consume independently replayed summaries, never model self-ratings.

    A missing test category is BLOCK, not vacuous PASS. Feedback compares the
    same initial task with differing observations; path diversity compares
    repeated rollouts of the SAME task, not different task templates.
    """
    if not 0 < min_success <= 1 or not 0 < min_schema <= 1 or min(min_pairs, min_repair, min_families) < 1:
        raise ValueError("positive nontrivial gate thresholds required")
    if not rows:
        return blocked_gate("No independently replayed model episodes")
    calls = sum(row["calls"] for row in rows)
    schema_calls = sum(row["schema_valid_calls"] for row in rows)
    families = {row["family"] for row in rows}
    success_count = sum(row["success"] for row in rows)
    relevant_count = sum(row["relevant"] for row in rows)
    repairs = [row for row in rows if row["repair_opportunity"]]
    repair_tasks = {row["task_id"] for row in repairs}
    repaired = sum(row["repair_success"] for row in repairs)
    pairs, paths = defaultdict(list), defaultdict(set)
    for row in rows:
        pairs[row["pair_id"]].append(row)
        if row["success"]:
            paths[row["task_id"]].add(tuple(row["path"]))
    pair_checks = []
    for key, pair in pairs.items():
        available = [row for row in pair if row["side"] == "available"]
        missing = [row for row in pair if row["side"] == "view_without_target"]
        if not available or not missing:
            continue
        passed = any(feedback_continuation_changed(a, b) for a in available for b in missing)
        pair_checks.append({"pair_id": key, "passed": passed})
    feedback_ok = len(pair_checks) >= min_pairs and sum(p["passed"] for p in pair_checks) / max(1, len(pair_checks)) >= min_success
    repair_ok = len(repair_tasks) >= min_repair and repaired / max(1, len(repairs)) >= min_success
    multipath_tasks = sorted(key for key, values in paths.items() if len(values) >= 2)
    enough_families = len(families) >= min_families
    checks = [
        {"id": "tool_understanding", "status": "PASS" if enough_families and relevant_count / len(rows) >= min_success else "FAIL",
         "n": len(rows), "correct": relevant_count, "threshold": min_success,
         "scope": "Operational relevance to the declared task kind and actually used source/result; not proof of internal semantic understanding."},
        {"id": "schema_arguments", "status": "PASS" if calls and schema_calls / calls >= min_schema else "FAIL",
         "calls": calls, "valid": schema_calls, "threshold": min_schema,
         "denominator": "All policy action attempts, including invalid JSON and budget stops; not a count of successfully dispatched tools."},
        {"id": "feedback_adaptation", "status": "PASS" if feedback_ok and repair_ok else "BLOCK" if len(repair_tasks) < min_repair or len(pair_checks) < min_pairs else "FAIL",
         "paired_states": len(pair_checks), "paired_success": sum(p["passed"] for p in pair_checks),
         "repair_opportunities": len(repairs), "repair_successes": repaired,
         "distinct_repair_tasks": len(repair_tasks),
         "minimum_pairs": min_pairs, "minimum_repair_cases": min_repair,
         "note": "Requires the same action prefix up to changed tool feedback, then distinct successful continuations AND a tested repair opportunity. Unmatched stochastic first actions alone do not establish feedback use or a causal effect."},
        {"id": "end_to_end", "status": "PASS" if enough_families and success_count / len(rows) >= min_success else "FAIL",
         "n": len(rows), "successes": success_count, "threshold": min_success,
         "task_families": sorted(families), "minimum_task_families": min_families,
         "group_bootstrap": grouped_interval(rows, "group_id")},
    ]
    multi = {"status": "PASS" if multipath_tasks else "BLOCK", "tasks_with_two_successful_policy_paths": multipath_tasks,
        "note": "Different tasks and duplicated traces do not establish same-task multi-path policy choices. CPU reference paths alone do not pass."}
    passed = all(item["status"] == "PASS" for item in checks) and multi["status"] == "PASS"
    return {"passed": passed, "status": "PASS" if passed else "BLOCK", "checks": checks,
            "multipath_environment_gate": multi, "paired_state_details": pair_checks,
            "thresholds_are_exploratory_not_a_scientific_release_standard": True}


def rp_audit(report_path: Path, model: Path, adapter: Path, data_dir: Path,
             train_data: Path, *, min_success: float = .9, min_schema: float = 1.0,
             min_pairs: int = 2, min_repair: int = 2, min_families: int = 2) -> dict:
    """Recompute actual model-token/prompt, tool and terminal-result contracts."""
    sys.path.insert(0, str(ROOT))
    try:
        from rp_grpo import environment, train_policy
        from transformers import AutoTokenizer
        report_path = report_path.resolve(strict=True)
        manifest = read_json(report_path)
        if manifest.get("mode") != "evaluate" or manifest.get("status") != "completed":
            raise ValueError("need a complete actual policy evaluation manifest")
        if manifest.get("record_source") != "actual_hf_model":
            raise ValueError("reference/replay/synthetic outputs are not model readiness evidence")
        if manifest.get("arm") == "B0":
            raise ValueError("rule-overridden B0 is a system baseline, not the SFT policy gate")
        snapshot = train_policy.model_snapshot(model)
        adapter_info = train_policy.adapter_snapshot(adapter)
        bindings = {
            "base_snapshot_sha256": snapshot["snapshot_sha256"],
            "initial_adapter_sha256": adapter_info["snapshot_sha256"],
            "training_data_sha256": file_hash(train_data),
            "scorers_sha256": file_hash(data_dir / "scorers.jsonl"),
            "data_manifest_sha256": file_hash(data_dir / "MANIFEST.json"),
            "environment_sha256": file_hash(Path(environment.__file__)),
            "prompt_contract_sha256": train_policy.prompt_contract(snapshot)["sha256"],
        }
        if any(manifest.get("bindings", {}).get(key) != value for key, value in bindings.items()):
            raise ValueError("evaluation is bound to different base/adapter/data/environment/prompt")
        for name in ("rp_grpo/train_policy.py", "rp_grpo/environment.py", "rp_grpo/build_data.py"):
            if manifest.get("code_files_sha256", {}).get(name) != file_hash(ROOT / name):
                raise ValueError(f"actual evaluation implementation changed: {name}")
        episodes_path = report_path.parent / "episodes.jsonl"
        if file_hash(episodes_path) != manifest.get("episodes_sha256"):
            raise ValueError("actual model episodes hash mismatch")
        episodes = read_jsonl(episodes_path)
        config = manifest["config"]
        if manifest.get("config_sha256") != canonical_hash(config):
            raise ValueError("evaluation configuration hash mismatch")
        tasks_list = train_policy.load_tasks(train_data, manifest["split"])
        if manifest["split"] != "dev":
            raise ValueError("SFT admission must use development, not training or historical test")
        tasks = {task["id"]: task for task in tasks_list}
        expected_ids = Counter({task["id"]: int(config["eval_rollouts"])
                               for task in tasks_list[:int(config["max_eval_tasks"])]})
        if Counter(row["task_id"] for row in episodes) != expected_ids:
            raise ValueError("missing/extra model episodes relative to planned development selection")
        expected_draws = Counter((task["id"], int(config["seed"]) + index * 10000 + repeat * 100)
            for index, task in enumerate(tasks_list[:int(config["max_eval_tasks"])])
            for repeat in range(int(config["eval_rollouts"])))
        if Counter((row["task_id"], row.get("seed")) for row in episodes) != expected_draws:
            raise ValueError("missing/duplicated policy draws relative to the frozen seed plan")
        tokenizer = AutoTokenizer.from_pretrained(model, local_files_only=True, trust_remote_code=False)
        if (manifest.get("generation_pad_token_id") != tokenizer.eos_token_id
                or manifest.get("generation_eos_token_id") != tokenizer.eos_token_id):
            raise ValueError("generation padding/EOS differs from the deployed base tokenizer contract")
        results = []
        for episode in episodes:
            task = tasks[episode["task_id"]]
            trace = episode.get("environment_trace")
            if not isinstance(trace, dict):
                raise ValueError("actual model episode lacks environment execution trace")
            if trace.get("max_steps") != config["max_turns"]:
                raise ValueError("environment budget differs from evaluation configuration")
            replay = environment.replay_trace(trace, data_dir=data_dir)
            if not replay["valid"]:
                raise ValueError("environment trace failed independent replay: " + str(replay["errors"]))
            env = environment.ResearchEnvironment(data_dir=data_dir, max_steps=trace["max_steps"])
            initial = env.reset(task)
            if initial != episode.get("initial_observation"):
                raise ValueError("model initial observation differs from authorized environment")
            messages = train_policy.initial_messages(initial)
            if canonical_hash(messages) != episode.get("initial_prompt_sha256"):
                raise ValueError("initial prompt does not match actual public state")
            actions, observations, valid_calls, calls = [], [], 0, 0
            useful = False
            feedback = initial.get("previous_tool_feedback") or {}
            repair_opportunity = feedback.get("observation", {}).get("status") == "invalid_action"
            repair_changed = False
            invalid_before = None
            acquisition = None
            for step in episode["steps"]:
                calls += 1
                if messages != step.get("messages"):
                    raise ValueError("recorded policy prompt is not its actual prior tool feedback")
                prompt = train_policy.format_prompt(tokenizer, messages)
                if canonical_hash(prompt) != step.get("prompt_sha256"):
                    raise ValueError("serialized policy prompt hash mismatch")
                validate_policy_tokens(step, tokenizer, prompt, episode, config)
                if not step["terminated"]:
                    if "action" in step or "result" in step:
                        raise ValueError("truncated generation was executed")
                    break
                try:
                    action = train_policy.parse_action(step["raw_text"])
                except ValueError:
                    if "action" in step or "result" in step:
                        raise ValueError("invalid raw JSON was silently repaired/executed")
                    break
                if action != step.get("action"):
                    raise ValueError("executed action differs from actual model JSON")
                result = env.step(action)
                if canonical_hash(result) != canonical_hash(step.get("result")):
                    raise ValueError("recorded tool observation/reward differs from independent execution")
                actions.append(canonical_hash(action))
                observations.append(canonical_hash(result["observation"]))
                obs = result["observation"]
                if obs.get("status") != "invalid_action":
                    valid_calls += 1
                    if invalid_before is not None and canonical_hash(action) != invalid_before:
                        repair_changed = True
                else:
                    repair_opportunity = True
                    invalid_before = canonical_hash(action)
                if acquisition is None and action["tool"] in {"search_evidence", "list_documents", "read_passage", "query_metrics"}:
                    acquisition = action["tool"]
                if task["task_kind"] == "text_evidence":
                    useful |= action["tool"] in {"search_evidence", "list_documents", "read_passage"} and obs.get("status") == "ok"
                else:
                    useful |= action["tool"] == "query_metrics" and obs.get("status") in {"ok", "unavailable_in_authorized_snapshot"}
                if result["done"]:
                    break
                train_policy.append_observation(messages, step["raw_text"], action, result)
            if calls != len(episode["steps"]):
                raise ValueError("extra model calls recorded after a terminal/unexecutable response")
            rebuilt = env.export_trace()
            if replay_content(rebuilt) != replay_content(trace):
                raise ValueError("model actions do not reproduce the supplied environment trace")
            succeeded = bool((rebuilt.get("terminal") or {}).get("passed"))
            if episode["done"] != rebuilt["done"]:
                raise ValueError("claimed episode lifecycle differs from actual environment")
            if rebuilt["done"] and episode["reward"] != rebuilt["reward"]:
                raise ValueError("claimed final reward differs from actual environment")
            if repair_opportunity and invalid_before is None:
                # A real reset/setup error is repaired only through valid work,
                # never by declaring success or changing a status string.
                failed_setup = canonical_hash(feedback.get("action"))
                repair_changed = bool(actions and actions[0] != failed_setup and valid_calls == calls and useful)
            final = (rebuilt.get("terminal") or {}).get("dimensions", {})
            relevant = useful and final.get("not_premature", False) and final.get("actual_result", False)
            results.append({"task_id": task["id"], "pair_id": task["pair_id"], "side": task["side"],
                "group_id": task["group_id"], "family": task["task_kind"] + ":" + task["variant"],
                "success": succeeded, "relevant": relevant, "calls": calls, "schema_valid_calls": valid_calls,
                "executed_tool_calls": len(actions), "unexecuted_action_attempts": calls - len(actions),
                "repair_opportunity": repair_opportunity, "repair_success": repair_changed and succeeded,
                "initial_sha256": canonical_hash(initial), "observation_hashes": observations,
                "action_hashes": actions, "path": [acquisition or "none", task["task_kind"]],
                "trace_sha256": rebuilt["trace_sha256"], "terminal_dimensions": final,
                "termination_reason": episode["termination_reason"]})
        outcome = decision_checks(results, min_success=min_success, min_schema=min_schema,
            min_pairs=min_pairs, min_repair=min_repair, min_families=min_families)
        portable_report_path = str(report_path.relative_to(ROOT)) if report_path.is_relative_to(ROOT) else str(report_path)
        selected = tasks_list[:int(config["max_eval_tasks"])]
        selected_pairs = Counter(task["pair_id"] for task in selected)
        family_counts = Counter(task["task_kind"] + ":" + task["variant"] for task in selected)
        return {"schema": "mito.sft-readiness.rp-evaluation.v1", "created_at": datetime.now(timezone.utc).isoformat(),
            **outcome, "bindings": bindings, "source_evaluation_manifest": {"path": portable_report_path, "sha256": file_hash(report_path)},
            "source_episodes_sha256": file_hash(episodes_path), "auditor_sha256": file_hash(Path(__file__)),
            "new_model_inference_performed_by_this_audit": False, "actual_model_evaluation_verified": True,
            "episodes": results, "evaluated_episodes": len(results), "development_tasks": len(tasks),
            "coverage": {"unique_evaluated_tasks": len(selected), "planned_rollouts": sum(expected_ids.values()),
                "total_development_tasks": len(tasks), "complete_selected_pairs": sum(n == 2 for n in selected_pairs.values()),
                "partial_selected_pairs": sum(n == 1 for n in selected_pairs.values()), "unique_tasks_by_family": dict(family_counts),
                "distinct_source_groups": len({task["group_id"] for task in selected}),
                "selection": "Manifest-bound development input prefix; no post-outcome filtering.",
                "sampling": "stochastic" if config.get("eval_sample") else "greedy"},
            "full_development_coverage": set(expected_ids) == set(tasks),
            "limits": ["Engineering readiness, not unseen scientific generalization.",
                "Hashes and independent tool replay establish record consistency; they are not remote hardware attestation.",
                "A missing repair or same-task multi-path evaluation category remains blocked."]}
    finally:
        sys.path.remove(str(ROOT))


def parser():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--model-path", type=Path, default=ROOT / "models/Qwen3-4B-Instruct-2507")
    p.add_argument("--legacy-root", type=Path)
    p.add_argument("--adapter", type=Path)
    p.add_argument("--output", type=Path, default=ROOT / "rp_grpo/SFT_GATE.json")
    p.add_argument("--historical-output", type=Path)
    p.add_argument("--evaluation-report", type=Path)
    p.add_argument("--readiness-output", type=Path)
    p.add_argument("--data-dir", type=Path, default=ROOT / "rp_grpo/data")
    p.add_argument("--train-data", type=Path, default=ROOT / "rp_grpo/data/tasks.jsonl")
    p.add_argument("--min-success", type=float, default=.9)
    p.add_argument("--min-schema", type=float, default=1.0)
    p.add_argument("--min-pairs", type=int, default=2)
    p.add_argument("--min-repair", type=int, default=2)
    p.add_argument("--min-families", type=int, default=2)
    p.add_argument("--blocked-reason", help="Explain why no actual model evaluation was attempted; never changes admission.")
    p.add_argument("--execution-preflight", type=Path, help="Optional CPU-only resource observation, retained as non-admission context.")
    return p


def main():
    args = parser().parse_args()
    # Refuse a rerun before expensive hashing; audits are versioned artifacts.
    for path in (args.output, args.historical_output, args.readiness_output):
        if path is not None and (path.exists() or path.is_symlink()):
            raise ValueError(f"output already exists: {path}")
    history = legacy_audit(args.legacy_root, args.model_path, adapter=args.adapter) if args.legacy_root else None
    report = blocked_gate(args.blocked_reason or "No validated actual model rollout in the new RP harness is supplied.", legacy=history)
    # Historical attestation has a narrower hash scope; it must not populate
    # the new RP model/adapter binding fields even when its bytes match.
    if args.execution_preflight:
        report["execution_preflight"] = {"path": str(args.execution_preflight),
            "sha256": file_hash(args.execution_preflight), "record": read_json(args.execution_preflight),
            "is_model_admission_evidence": False}
    if args.historical_output:
        write_new(args.historical_output, history)
    if args.evaluation_report:
        if args.blocked_reason:
            raise ValueError("blocked-reason is only for an absent actual model evaluation")
        if args.readiness_output is None or args.adapter is None:
            raise ValueError("actual RP audit needs --adapter and --readiness-output")
        actual = rp_audit(args.evaluation_report, args.model_path, args.adapter, args.data_dir, args.train_data,
            min_success=args.min_success, min_schema=args.min_schema, min_pairs=args.min_pairs,
            min_repair=args.min_repair, min_families=args.min_families)
        write_new(args.readiness_output, actual)
        report.update({key: actual[key] for key in ("passed", "status", "checks", "multipath_environment_gate")})
        report["reason"] = "All operational admission checks passed." if actual["passed"] else "Actual RP model evaluation does not meet all admission checks."
        report["bindings"] = {**actual["bindings"], "evaluation_report_sha256": file_hash(args.readiness_output)}
        report["evaluation_report_sha256"] = file_hash(args.readiness_output)
        resolved = args.readiness_output.resolve()
        report["evaluation_report_path"] = str(resolved.relative_to(ROOT)) if resolved.is_relative_to(ROOT) else str(resolved)
        report["training_authorized_by_this_gate"] = actual["passed"]
    write_new(args.output, report)
    print(json.dumps({"output": str(args.output), "passed": report["passed"], "status": report["status"]}, ensure_ascii=False))
    return 0 if report["passed"] else 2


if __name__ == "__main__":
    sys.exit(main())
